export default function Home() {
  return (
    <main className="min-h-screen flex flex-col items-center justify-center gap-8 px-6">
      <div className="w-20 h-20 rounded-2xl bg-gradient-to-br from-eburon-500 to-purple-600 flex items-center justify-center shadow-lg shadow-eburon-500/30">
        <svg width="40" height="40" viewBox="0 0 24 24" fill="none" stroke="white" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
          <rect x="4" y="4" width="16" height="16" rx="2" />
          <path d="m9 9 6 6" />
          <path d="m15 9-6 6" />
        </svg>
      </div>

      <div className="text-center space-y-3 max-w-lg">
        <h1 className="text-4xl font-bold bg-gradient-to-r from-eburon-400 to-purple-400 bg-clip-text text-transparent">
          Eburon Client Apps
        </h1>
        <p className="text-gray-400 text-lg">
          This platform hosts applications generated by{" "}
          <span className="text-eburon-400 font-medium">Eburon Codepilot</span>.
        </p>
        <p className="text-gray-600 text-sm">
          Standby mode — ready to serve deployed client applications.
        </p>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 max-w-2xl w-full mt-4">
        {[
          { icon: "⚡", title: "Auto-Deploy", desc: "Apps deploy instantly after generation" },
          { icon: "🔗", title: "Unique URLs", desc: "Each app gets its own live endpoint" },
          { icon: "📦", title: "Version History", desc: "Every deployment tracked in Git" },
        ].map((f) => (
          <div key={f.title} className="p-4 rounded-xl border border-white/[0.06] bg-white/[0.02] text-center space-y-2">
            <span className="text-2xl">{f.icon}</span>
            <p className="text-sm font-medium text-white">{f.title}</p>
            <p className="text-xs text-gray-500">{f.desc}</p>
          </div>
        ))}
      </div>

      <footer className="mt-12 text-[11px] text-gray-700">
        © {new Date().getFullYear()} Eburon Technologies
      </footer>
    </main>
  );
}
